Fix connections between client-api and as servers
securekey/oauth-xyz-nodejs pull request #5
Opened 2019-12-08 13:29 UTC by corocn

Connection between client-api and AS containers failed.
I fixed asTransactionURL in routesController.
This PR and https://github.com/securekey/oauth-xyz-nodejs/pull/4 will make all servers launching and processing correctly with docker-compose.

2019-12-09 00:47 UTC, mavarley commented
Thank-you, we will review tomorrow and merge.

2019-12-09 16:38 UTC, haardikk21 commented
This was the old URL we were using. @jricher you changed it to the internal docker host URL. Can you weigh in on this change?

2019-12-09 17:17 UTC, jricher commented
Sorry about that, that change was done during testing against the Java implementation. It wasn't supposed to be pushed, so putting it back is fine. That said, the URL should be an external one, right? So it's `localhost:3000` and not `as:3000` with the link, since the transaction endpoint is intended to be exposed.

2019-12-09 18:46 UTC, haardikk21 commented
> Sorry about that, that change was done during testing against the Java implementation. It wasn't supposed to be pushed, so putting it back is fine. That said, the URL should be an external one, right? So it's `localhost:3000` and not `as:3000` with the link, since the transaction endpoint is intended to be exposed.

In this specific scenario, since the included client is the only one talking to the server, the internal URL would still work. Also I believe the ports are being exposed in the docker compose so the localhost URL will also work.

For consistency purposes I think we should switch to using localhost. @corocn can you update it accordingly and I will merge then.

2019-12-09 19:59 UTC, jricher commented
While a local `link` would technically work with this, it is not the correct style of connection that this application should be using. The client and AS should be separate entities entirely, and the fact that they're packaged together in one docker container is a side effect, not a feature.

2019-12-09 19:59 UTC, jricher requested changes

2019-12-09 19:59 UTC, jricher commented on client/api/src/controllers/routesController.ts
> +const asTransactionURL = 'http://as:3000/transaction';
```suggestion
const asTransactionURL = 'http://localhost:3000/transaction';
```

2019-12-09 19:59 UTC, jricher commented on docker-compose.yml
> +      - as
```suggestion

```

2019-12-10 00:51 UTC, corocn commented
> The client and AS should be separate entities entirely, and the fact that they're packaged together in one docker container is a side effect, not a feature

I got it and updated my pull requests using localhost:3000.
Thank you.

2019-12-10 16:44 UTC, jricher approved these changes

2019-12-10 16:50 UTC, merged

2021-03-11 19:39 UTC, Neha261289 commented
I cloned this repo and tried to bring local env up, but i am getting errors when running docker-compose up , I am seeing 97 errors in my terminal. Can someone please help me with running my local instance of this repo. I am intending to contribute to this project.